version: '3.8'

services:
  data-engine:
    image: jupyter/pyspark-notebook:latest
    container_name: logixpress_container
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    user: root
    environment:
      - PYTHONPATH=/home/jovyan/work
    command: >
      bash -c "pip install --no-cache-dir -r /home/jovyan/work/requirements.txt &&
      start-notebook.sh --NotebookApp.token=''"